export interface ITicketDevice {
  id: string;
  company_id: string;
  contract_id: string;
  service_id: string;
  location_id: string;
  site_id: string;
  code: string;
  name: string;
  description: string;
  serialnumber: string;
  productnumber: string;
  brand: string;
  ip: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  x1: null;
  x2: null;
  x3: null;
  x4: null;
  x5: null;
  x6: null;
  x7: null;
  x8: null;
  x9: null;
  x10: null;
  x11: null;
  x12: null;
  x13: null;
  x14: null;
  x15: null;
  x16: null;
  x17: null;
  x18: null;
  x19: null;
  x20: null;
}

export interface ITicket {
  id: string;
  user_id: string;
  company_id: string;
  contract_id: string;
  site_id: string;
  attendance_id: string;
  evidence_group_id: string;
  severity_id: string;
  device_id: string;
  status_id: string;
  code: string;
  name: string;
  description: string;
  start_ticket: string;
  end_ticket: string;
  created_at: string;
  updated_at: string;
  deleted_at: string;
  x1: null;
  x2: null;
  x3: null;
  x4: null;
  x5: null;
  x6: null;
  x7: null;
  x8: null;
  x9: null;
  x10: null;
  x11: null;
  x12: null;
  x13: null;
  x14: null;
  x15: null;
  x16: null;
  x17: null;
  x18: null;
  x19: null;
  x20: null;
}

export interface ITicketUser {
  id: string;
  company_id: null | string;
  role_id: string;
  contract_id: null | string;
  location_id: null | string;
  site_id: null | string;
  code: string;
  name: string;
  email: string;
  password: string;
  phone: null | number;
  start_user: null | string;
  end_user: null | string;
  first_login: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  x1: null;
  x2: null;
  x3: null;
  x4: null;
  x5: null;
  x6: null;
  x7: null;
  x8: null;
  x9: null;
  x10: null;
  x11: null;
  x12: null;
  x13: null;
  x14: null;
  x15: null;
  x16: null;
  x17: null;
  x18: null;
  x19: null;
  x20: null;
}

export interface ITicketSite {
  id: string;
  company_id: string;
  contract_id: string;
  location_id: string;
  code: string;
  name: string;
  description: string;
  longitude: number;
  latitude: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  x1: null;
  x2: null;
  x3: null;
  x4: null;
  x5: null;
  x6: null;
  x7: null;
  x8: null;
  x9: null;
  x10: null;
  x11: null;
  x12: null;
  x13: null;
  x14: null;
  x15: null;
  x16: null;
  x17: null;
  x18: null;
  x19: null;
  x20: null;
  tolerance: number;
}

export interface ITicketEvid {
  id: string;
  evidence_group_id: string;
  code: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  x1: null;
  x2: null;
  x3: null;
  x4: null;
  x5: null;
  x6: null;
  x7: null;
  x8: null;
  x9: null;
  x10: null;
  x11: null;
  x12: null;
  x13: null;
  x14: null;
  x15: null;
  x16: null;
  x17: null;
  x18: null;
  x19: null;
  x20: null;
  file: string;
}

export interface ITicketContract {
  id: string;
  company_id: string;
  code: string;
  number: string;
  name: string;
  description: string;
  contract_file: string;
  start_contract: string;
  end_contract: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  x1: null;
  x2: null;
  x3: null;
  x4: null;
  x5: null;
  x6: null;
  x7: null;
  x8: null;
  x9: null;
  x10: null;
  x11: null;
  x12: null;
  x13: null;
  x14: null;
  x15: null;
  x16: null;
  x17: null;
  x18: null;
  x19: null;
  x20: null;
}

export interface ITicketSeverity {
  id: string;
  code: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  x1: null;
  x2: null;
  x3: null;
  x4: null;
  x5: null;
  x6: null;
  x7: null;
  x8: null;
  x9: null;
  x10: null;
  x11: null;
  x12: null;
  x13: null;
  x14: null;
  x15: null;
  x16: null;
  x17: null;
  x18: null;
  x19: null;
  x20: null;
  timer: number;
  color: string;
}

export interface ITicketDevice {
  id: string;
  company_id: string;
  contract_id: string;
  service_id: string;
  location_id: string;
  site_id: string;
  code: string;
  name: string;
  description: string;
  serialnumber: string;
  productnumber: string;
  brand: string;
  ip: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  x1: null;
  x2: null;
  x3: null;
  x4: null;
  x5: null;
  x6: null;
  x7: null;
  x8: null;
  x9: null;
  x10: null;
  x11: null;
  x12: null;
  x13: null;
  x14: null;
  x15: null;
  x16: null;
  x17: null;
  x18: null;
  x19: null;
  x20: null;
}

export interface ITicketStatus {
  id: string;
  code: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  x1: null;
  x2: null;
  x3: null;
  x4: null;
  x5: null;
  x6: null;
  x7: null;
  x8: null;
  x9: null;
  x10: null;
  x11: null;
  x12: null;
  x13: null;
  x14: null;
  x15: null;
  x16: null;
  x17: null;
  x18: null;
  x19: null;
  x20: null;
}

export interface IAttendanceOptions {
  id: string;
  company_id: string;
  contract_id: string;
  user_id: string;
  site_id: string;
  evidence_group_id: string;
  code: string;
  name: string;
  description: string;
  longitude: number;
  langitude: null;
  checkin: string;
  checkout: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  x1: null;
  x2: null;
  x3: null;
  x4: null;
  x5: null;
  x6: null;
  x7: null;
  x8: null;
  x9: null;
  x10: null;
  x11: null;
  x12: null;
  x13: null;
  x14: null;
  x15: null;
  x16: null;
  x17: null;
  x18: null;
  x19: null;
  x20: null;
  attendance_status_id: string;
}

export type TTicket = {
  user_id: string;
  company_id: string;
  contract_id: string;
  site_id: string;
  code: string;
  status_id: string;
  start_ticket: string;
  attendance_id: string;
  evidence_group_id: string;
  severity_id: string;
  device_id: string;
  name: string;
  description: string;
};
